### ISSUE TITLE
sharing encrypted text results in empty screen on Delta Chat desktop

### ISSUE THREAD

**Issue by hpk42** [DavidSM100/CryptoText#2]
When i produce an encrypted text i can share it with Android (1.40.0) but on Desktop it results in an empty screen  -- in the debugging view i don't see any particular exception, unfortunately.

**Comment by davidsm10** [comment]
Hello, I don't have a PC, so I couldn't test the webxdc there, but I believe 
that issue is a desktop version issue that doesn't depend on me, I believe 
Adb reported it already, anyway I will try to see what happens when the 
app is opened en a PC so I will see if it's a different issue. If you could 
send some screenshots to ***@***.*** , that would be helpful.

**Comment by hpk42** [comment]
![image](https://github.com/DavidSM100/CryptoText/assets/73579/c8984216-e49d-4eb5-af00-774dca780d52)
when i click "share" button on encrypted text then the next screen is this: 
![image](https://github.com/DavidSM100/CryptoText/assets/73579/a56063f6-6b55-4018-bb37-e82fb3faf0f2)

**Comment by davidsm10** [comment]
Yes, confirmed, it's a desktop version problem, I think adb open an issue for that bug, so there is nothing I can do about it, just wait for a new version of DC desktop with the bug fixed. So I suppose I can close this issue?

**Comment by davidsm10** [comment]
> Yes, confirmed, it's a desktop version problem, I think adb open an issue for that bug, so there is nothing I can do about it, just wait for a new version of DC desktop with the bug fixed. So I suppose I can close this issue?

Just to let anyone interested know, I now see that the issue can be solved using the webxdc API (sendToChat) to share the texts instead of the previous way that was mailto links which caused the bug.
So this is solved now, even though the desktop bug still exists.
The new version is available on the xstore.
